version: '3'
services:

    web:
        image: 'kyrylo_kundik_hw'
        build: .
        container_name: web_ml_rr
        environment:
            - POSTGRES_PASSWORD
            - POSTGRES_USER
            - POSTGRES_DB
        ports:
            - '8088:8088'
        volumes:
            - .:/kyrylo_kundik_hw
        links:
            - postgres
        restart: always
        depends_on:
            - postgres
        networks:
            - pg_net
    crawler:
        image: 'kyrylo_kundik_hw_crawler'
        build:
            context: '.'
            dockerfile: 'Dockerfile-crawler'
        container_name: web_ml_rr_crawler
        environment:
            - POSTGRES_PASSWORD
            - POSTGRES_USER
            - POSTGRES_DB
        volumes:
          - .:/kyrylo_kundik_hw
        links:
          - postgres
        depends_on:
          - postgres
        networks:
          - pg_net
    postgres:
        image: postgres:9.6
        container_name: postgres_ml_rr
        environment:
            - POSTGRES_PASSWORD
            - POSTGRES_USER
            - POSTGRES_DB
        ports:
            - "5432:5432"
        restart: always
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 10s
            timeout: 5s
            retries: 5
        networks:
            - pg_net
networks:
    pg_net:
