import scrapy


class Apartment(scrapy.Item):
    title = scrapy.Field()
    creation_date = scrapy.Field()
    price = scrapy.Field()
    price_uah = scrapy.Field()
    images = scrapy.Field()
    description = scrapy.Field()
    street_name = scrapy.Field()
    state_name = scrapy.Field()
    total_square_meters = scrapy.Field()
    living_square_meters = scrapy.Field()
    kitchen_square_meters = scrapy.Field()
    rooms_count = scrapy.Field()
    floor = scrapy.Field()
    wall_type = scrapy.Field()
    inspected = scrapy.Field()
    verified_price = scrapy.Field()
    latitude = scrapy.Field()
    longitude = scrapy.Field()
    construction_year = scrapy.Field()
    heating = scrapy.Field()
    seller = scrapy.Field()
    water = scrapy.Field()
    building_condition = scrapy.Field()
    dist_to_center = scrapy.Field()
    dist_to_kindergarten = scrapy.Field()
    dist_to_school = scrapy.Field()
    dist_to_hospital = scrapy.Field()
    dist_to_bus_station = scrapy.Field()
    dist_to_railway_station = scrapy.Field()
    dist_to_airport = scrapy.Field()