"""empty message

Revision ID: 0c797197f896
Revises: ad15f030a15a
Create Date: 2019-08-11 13:02:30.831861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c797197f896'
down_revision = 'ad15f030a15a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apartment', sa.Column('floors_count', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('apartment', 'floors_count')
    # ### end Alembic commands ###
