"""empty message

Revision ID: 2a2d5752d9ee
Revises: 91742950bfd3
Create Date: 2019-08-11 13:20:34.315671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a2d5752d9ee'
down_revision = '91742950bfd3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('apartment', 'price_uah')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apartment', sa.Column('price_uah', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
