"""empty message

Revision ID: 91742950bfd3
Revises: 0c797197f896
Create Date: 2019-08-11 13:14:58.067787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91742950bfd3'
down_revision = '0c797197f896'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apartment_images', sa.Column('apartment_fk', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'apartment_images', 'apartment', ['apartment_fk'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.add_column('seller_info', sa.Column('apartment_fk', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'seller_info', 'apartment', ['apartment_fk'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'seller_info', type_='foreignkey')
    op.drop_column('seller_info', 'apartment_fk')
    op.drop_constraint(None, 'apartment_images', type_='foreignkey')
    op.drop_column('apartment_images', 'apartment_fk')
    # ### end Alembic commands ###
