"""empty message

Revision ID: ad15f030a15a
Revises: a654e823ff0c
Create Date: 2019-08-11 12:59:38.278366

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad15f030a15a'
down_revision = 'a654e823ff0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apartment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('created_at', sa.Date(), nullable=True),
    sa.Column('price_usd', sa.Integer(), nullable=True),
    sa.Column('price_uah', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('street_name', sa.String(), nullable=True),
    sa.Column('state_name', sa.String(), nullable=True),
    sa.Column('city_name', sa.String(), nullable=True),
    sa.Column('total_square_meters', sa.Float(), nullable=True),
    sa.Column('living_square_meters', sa.Float(), nullable=True),
    sa.Column('kitchen_square_meters', sa.Float(), nullable=True),
    sa.Column('rooms_count', sa.Integer(), nullable=True),
    sa.Column('floor', sa.String(), nullable=True),
    sa.Column('wall_type', sa.String(), nullable=True),
    sa.Column('inspected', sa.String(), nullable=True),
    sa.Column('verified_price', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('construction_year', sa.String(), nullable=True),
    sa.Column('heating', sa.String(), nullable=True),
    sa.Column('seller', sa.String(), nullable=True),
    sa.Column('water', sa.String(), nullable=True),
    sa.Column('building_condition', sa.String(), nullable=True),
    sa.Column('dist_to_center', sa.String(), nullable=True),
    sa.Column('dist_to_railway_station', sa.String(), nullable=True),
    sa.Column('dist_to_airport', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('apartment_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('link_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('seller_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('admin')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('pass_hash', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='admin_pkey')
    )
    op.drop_table('seller_info')
    op.drop_table('apartment_images')
    op.drop_table('apartment')
    # ### end Alembic commands ###
